services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./volumes/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:rw
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      TZ: 'Europe/Warsaw'
      DISABLE_JEMALLOC: 'true'
    depends_on:
      - traefik
      - matter-server
      - music-assistant

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./volumes/matter-server:/data
      - /run/dbus:/run/dbus:ro

  music-assistant:
    container_name: music-assistant
    image: ghcr.io/music-assistant/server:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/music-assistant:/data
    environment:
      TZ: 'Europe/Warsaw'
