services:
  ryot-db:
    image: postgres:18-alpine
    container_name: ryot-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${RYOT_DB_PASSWORD}
    volumes:
      - ryot_postgres:/var/lib/postgresql
    networks:
      - proxy

  ryot:
    image: ignisda/ryot:v10
    container_name: ryot
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - SERVER_ADMIN_ACCESS_TOKEN=${RYOT_ADMIN_ACCESS_TOKEN}
      - DATABASE_URL=postgres://postgres:${RYOT_DB_PASSWORD}@ryot-db:5432/postgres
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ryot.rule=Host(`ryot.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.ryot.entrypoints=https"
      - "traefik.http.routers.ryot.tls.certresolver=le"
    depends_on:
      - ryot-db
      - traefik

volumes:
  ryot_postgres:
