services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Warsaw
    volumes:
      - /volume2/docker/sonarr:/config
      - /volume2/media:/data
    ports:
      - 8989:8989
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Warsaw
    volumes:
      - /volume2/docker/radarr:/config
      - /volume2/media:/data
    ports:
      - 7878:7878
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Warsaw
    volumes:
      - /volume2/docker/prowlarr:/config
    ports:
      - 9696:9696
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always