services:
  tautulli:
    container_name: tautulli
    image: ghcr.io/tautulli/tautulli
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - tautili:/config
    ports:
      - 8181:8181
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.routers.tautulli.tls.certresolver=le"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"

volumes:
  tautili:

networks:
  proxy:
    external: true