services:
  grafana:
    restart: unless-stopped
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=pkarpovich
      - GF_SECURITY_ADMIN_PASSWORD=wTest100*
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=Grafana
      - GF_SMTP_SKIP_VERIFY=false
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls.certresolver=le"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    restart: unless-stopped
    container_name: influxdb
    image: influxdb:2.7-alpine
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORGANIZATION}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influxdb:/var/lib/influxdb2
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influx.rule=Host(`influx.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.influx.entrypoints=https"
      - "traefik.http.routers.influx.tls.certresolver=le"
      - "traefik.http.services.influx.loadbalancer.server.port=8086"

  telegraf:
    container_name: telegraf
    restart: unless-stopped
    image: telegraf:1.35-alpine
    volumes:
      - ./.config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - proxy
    environment:
      - INFLUX_HOSTNAME=influxdb
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_ORGANIZATION=${INFLUX_ORGANIZATION}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - OPENWEATHER_CITY_ID=${OPENWEATHER_CITY_ID}

  prometheus:
    restart: unless-stopped
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - prometheus:/prometheus
      - ./.config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.prometheus.entrypoints=https"
      - "traefik.http.routers.prometheus.tls.certresolver=le"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  whoami:
    container_name: whoami
    image: mendhak/http-https-echo:33
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`info.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls.certresolver=le"

  tempo-init:
    image: busybox:latest
    user: root
    entrypoint:
      - chown
      - "10001:10001"
      - /var/tempo
    volumes:
      - tempo:/var/tempo

  tempo:
    restart: unless-stopped
    container_name: tempo
    image: grafana/tempo:2.10.0
    command: ["-config.file=/etc/tempo.yaml"]
    depends_on:
      tempo-init:
        condition: service_completed_successfully
    volumes:
      - ./.config/tempo.yaml:/etc/tempo.yaml:ro
      - ./.config/tempo-overrides.yaml:/etc/tempo-overrides.yaml:ro
      - tempo:/var/tempo
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tempo.rule=Host(`tempo.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.tempo.entrypoints=https"
      - "traefik.http.routers.tempo.tls.certresolver=le"
      - "traefik.http.services.tempo.loadbalancer.server.port=3200"

  loki:
    restart: unless-stopped
    container_name: loki
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/loki-config.yml"]
    volumes:
      - ./.config/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki:/loki
    ports:
      - "3100:3100"
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.loki.entrypoints=https"
      - "traefik.http.routers.loki.tls.certresolver=le"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"

  mcp-grafana:
    restart: unless-stopped
    container_name: mcp-grafana
    image: grafana/mcp-grafana:latest
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_SERVICE_ACCOUNT_TOKEN=${GRAFANA_SERVICE_ACCOUNT_TOKEN}
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.mcp-grafana.rule=Host(`mcp-grafana.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.mcp-grafana.entrypoints=https"
      - "traefik.http.routers.mcp-grafana.tls.certresolver=le"
      - "traefik.http.services.mcp-grafana.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true

volumes:
  grafana:
  influxdb:
  prometheus:
  tempo:
  loki:
