services:
  updater:
    container_name: updater
    image: ghcr.io/umputun/updater:latest
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${UPDATER_CONFIG_DIR:-./.config/updater}:/config:ro
      - ${UPDATER_SSH_KEY:-/home/app/.ssh/id_rsa}:/home/app/.ssh/id_rsa:ro
    expose:
      - 8080
    networks:
      - proxy
    environment:
      - CONF=/config/updater.yml
      - KEY=${UPDATER_KEY}
      - LISTEN=0.0.0.0:8080
      - TZ=Europe/Warsaw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.updater.rule=Host(`updater.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.updater.entrypoints=https"
      - "traefik.http.routers.updater.tls.certresolver=le"
