services:
  solidtime-app:
    image: solidtime/solidtime:latest
    container_name: solidtime-app
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${SOLIDTIME_APP_KEY}
      - APP_URL=https://solidtime.${ROOT_DOMAIN}
      - APP_FORCE_HTTPS=true
      - SUPER_ADMINS=${SOLIDTIME_SUPER_ADMINS}
      - DB_CONNECTION=pgsql
      - DB_HOST=solidtime-db
      - DB_PORT=5432
      - DB_DATABASE=solidtime
      - DB_USERNAME=solidtime
      - DB_PASSWORD=${SOLIDTIME_DB_PASSWORD}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
      - FILESYSTEM_DISK=local
      - MAIL_MAILER=${MAIL_MAILER:-log}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME="Solidtime"
      - GOTENBERG_URL=http://solidtime-gotenberg:3000
      - LOG_CHANNEL=stderr_daily
      - LOG_LEVEL=debug
      - TRUSTED_PROXIES=*
      - PUBLIC_FILESYSTEM_DISK=public
    volumes:
      - solidtime-app-storage:/var/www/html/storage
    networks:
      - proxy
      - solidtime-internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.solidtime.rule=Host(`solidtime.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.solidtime.entrypoints=https"
      - "traefik.http.routers.solidtime.tls.certresolver=le"
      - "traefik.http.services.solidtime.loadbalancer.server.port=8000"
    depends_on:
      - solidtime-db
      - traefik

  solidtime-scheduler:
    image: solidtime/solidtime:latest
    container_name: solidtime-scheduler
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - CONTAINER_MODE=scheduler
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${SOLIDTIME_APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=solidtime-db
      - DB_PORT=5432
      - DB_DATABASE=solidtime
      - DB_USERNAME=solidtime
      - DB_PASSWORD=${SOLIDTIME_DB_PASSWORD}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
      - FILESYSTEM_DISK=local
    volumes:
      - solidtime-app-storage:/var/www/html/storage
    networks:
      - solidtime-internal
    depends_on:
      - solidtime-db

  solidtime-queue:
    image: solidtime/solidtime:latest
    container_name: solidtime-queue
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - CONTAINER_MODE=worker
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${SOLIDTIME_APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=solidtime-db
      - DB_PORT=5432
      - DB_DATABASE=solidtime
      - DB_USERNAME=solidtime
      - DB_PASSWORD=${SOLIDTIME_DB_PASSWORD}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
      - FILESYSTEM_DISK=local
    volumes:
      - solidtime-app-storage:/var/www/html/storage
    networks:
      - solidtime-internal
    depends_on:
      - solidtime-db

  solidtime-db:
    image: postgres:15
    container_name: solidtime-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=solidtime
      - POSTGRES_USER=solidtime
      - POSTGRES_PASSWORD=${SOLIDTIME_DB_PASSWORD}
    volumes:
      - solidtime-db-data:/var/lib/postgresql/data
    networks:
      - solidtime-internal

  solidtime-gotenberg:
    image: gotenberg/gotenberg:8
    container_name: solidtime-gotenberg
    restart: unless-stopped
    networks:
      - solidtime-internal

networks:
  solidtime-internal:
    name: solidtime-internal
    driver: bridge

volumes:
  solidtime-db-data:
    name: solidtime-db-data
  solidtime-app-storage:
    name: solidtime-app-storage
