services:
  stash:
    container_name: stash
    image: ghcr.io/umputun/stash:latest
    restart: unless-stopped
    volumes:
      - ./volumes/stash:/data
    ports:
      - "127.0.0.1:9080:8080"
    networks:
      - proxy
    environment:
      - STASH_ADMIN_PASSWD=${STASH_ADMIN_PASSWD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stash.rule=Host(`stash.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.stash.entrypoints=https"
      - "traefik.http.routers.stash.tls.certresolver=le"

  updater:
    container_name: updater
    image: ghcr.io/umputun/updater:latest
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.config/updater:/config:ro
      - /home/app/.ssh/id_rsa:/home/app/.ssh/id_rsa:ro
    expose:
      - 8080
    networks:
      - proxy
    environment:
      - CONF=/config/updater.yml
      - KEY=${UPDATER_KEY}
      - LISTEN=0.0.0.0:8080
      - TZ=Europe/Warsaw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.updater.rule=Host(`updater.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.updater.entrypoints=https"
      - "traefik.http.routers.updater.tls.certresolver=le"
