services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    environment:
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - HEALTH_CHECK_URL=${HEALTH_CHECK_URL}
      - NAS_URL=${DISKSTATION_URL}
      - GITEA_URL=${GITEA_URL}
      - PLEX_URL=${PLEX_URL}
      - KIRA_CLIENT_URL=${KIRA_CLIENT_URL}
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    networks:
      - proxy
    ports:
      - 25:25
      - 80:80
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - letsencrypt:/letsencrypt
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=strip"
      - "traefik.http.middlewares.strip.stripprefix.prefixes=/traefik"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    depends_on:
      - traefik
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.jaeger.entrypoints=https"
      - "traefik.http.routers.jaeger.tls.certresolver=le"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"