services:
  authelia:
    container_name: authelia
    image: ghcr.io/authelia/authelia:4.39
    restart: unless-stopped
    healthcheck:
      interval: 5m
    expose:
      - 9091
    volumes:
      - ./authelia:/config:ro
      - authelia:/data
    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
    networks:
      - proxy
      - authelia
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`auth.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.authelia.entrypoints=https"
      - "traefik.http.routers.authelia.tls.certresolver=le"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/authz/forward-auth"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name"
    depends_on:
      traefik:
        condition: service_started
      authelia-redis:
        condition: service_healthy

  authelia-redis:
    container_name: authelia-redis
    image: redis:8-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5m
      start_period: 30s
      start_interval: 2s
    volumes:
      - authelia_redis:/data
    networks:
      - authelia

networks:
  proxy:
    external: true
  authelia:
    internal: true

volumes:
  authelia:
  authelia_redis:
