services:
  homepage:
    image: ghcr.io/benphelps/homepage:main
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homepage/config:/app/config
    environment:
      - HOMEPAGE_VAR_DISKSTATION_URL=${DISKSTATION_URL}
      - HOMEPAGE_VAR_DISKSTATION_USER=${DISKSTATION_USER}
      - HOMEPAGE_VAR_DISKSTATION_PASSWORD=${DISKSTATION_PASSWORD}
      - HOMEPAGE_VAR_HOMEBRIDGE_URL=${HOMEBRIDGE_URL}
      - HOMEPAGE_VAR_HOMEBRIDGE_USER=${HOMEBRIDGE_USER}
      - HOMEPAGE_VAR_HOMEBRIDGE_PASSWORD=${HOMEBRIDGE_PASSWORD}
      - HOMEPAGE_VAR_ZIMA_GRAFANA_URL=${ZIMA_GRAFANA_URL}
      - HOMEPAGE_VAR_ZIMA_GRAFANA_USER=${ZIMA_GRAFANA_USER}
      - HOMEPAGE_VAR_ZIMA_GRAFANA_PASSWORD=${ZIMA_GRAFANA_PASSWORD}

  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  iSponsorBlockTV:
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    container_name: iSponsorBlockTV
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./iSponsorBlockTV/config.json:/app/config.json
