apiVersion: 1
groups:
    - orgId: 1
      name: Temperature Data Missing Alert
      folder: Temperature Data
      interval: 15m
      rules:
        - uid: fewl9d6nif75sf
          title: Temperature Data Missing Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: victoriametrics
              model:
                datasource:
                    type: prometheus
                    uid: victoriametrics
                expr: count(homeassistant_sensor_temperature_celsius{entity=~"sensor.eve_weather_lr_temperature|sensor.bedroom_eve_weather_bedroom_temperature|sensor.eve_weather_20ebs9901_temperature"} and on(entity) (homeassistant_entity_available{entity=~"sensor.eve_weather_lr_temperature|sensor.bedroom_eve_weather_bedroom_temperature|sensor.eve_weather_20ebs9901_temperature"} == 1))
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 2
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            summary: Fewer than 2 of the 3 Eve room temperature sensors are reporting to VictoriaMetrics
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
