global:
  checkNewVersion: true

log:
  level: INFO

api:
  insecure: true
  dashboard: true

ping: { }

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

entryPoints:
  http:
    address: :80

  https:
    address: :443
    http:
      tls:
        certResolver: le
        domains:
          - main: '{{env "ROOT_DOMAIN"}}'
            sans:
              - '*.{{env "ROOT_DOMAIN"}}'

certificatesResolvers:
  le:
    acme:
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
      storage: /letsencrypt/acme.json

accessLog: { }
