global:
  checkNewVersion: true

log:
  level: WARN

api:
  insecure: true
  dashboard: true

ping: {}

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true

  https:
    address: :443
    http:
      tls:
        certResolver: le
        domains:
          - main: '{{env "ROOT_DOMAIN"}}'
            sans:
              - '*.{{env "ROOT_DOMAIN"}}'

certificatesResolvers:
  le:
    acme:
      dnsChallenge:
          provider: cloudflare
          resolvers:
            - "1.1.1.1:53"
            - "1.0.0.1:53"
      storage: /letsencrypt/acme.json
