---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
statusStyle: "dot"
layout:
  Media Management:
    icon: radarr-light
    style: row
    columns: 3

  Network and Data Management:
    style: column

  Monitoring:
    style: column

  Smart Home Integration:
    style: column

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
