useEqualHeights: true
color: neutral
layout:
  Media Hub:
    icon: mediathekview
    style: columns
    Plex Subgroup:
      header: false
      style: row
      columns: 2
    Synology:
      header: false
      style: row
      columns: 2
    Torrents:
      header: false
      style: row
      columns: 2
    Media Bookmarks:
      header: false
      style: row
      columns: 10
  Network & Storage:
    icon: pi-alert
    style: columns
    columns: 3
    Network:
      style: row
      columns: 2
      header: false
    DNS:
      style: row
      columns: 2
      header: false

  Observability & Health:
    icon: sh-fitbit-health-dashboard
    style: row
    columns: 4
  Weather:
    style: columns
    columns: 4
    header: false
  Bookmarks:
    header: false
    style: columns
    columns: 10
