---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
layout:
  Services:
    style: row
    columns: 2

  Zima:
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
