useEqualHeights: true
color: neutral
layout:
  Media Hub:
    icon: mediathekview
    style: columns
    Plex Subgroup:
      header: false
      style: row
      columns: 2
    Synology:
      header: false
      style: row
      columns: 2
    Torrents:
      header: false
      style: row
      columns: 2
  Home & Network:
    icon: pi-alert
    style: columns
    Network:
      header: false
      style: row
      columns: 2
    Hosts:
      header: false
      style: row
      columns: 2
    Home:
      header: false
      style: row
      columns: 2
  Dev & Agents:
    icon: gitea
    style: row
    columns: 4
  Health & Data:
    icon: sh-fitbit-health-dashboard
    style: row
    columns: 4
  Weather:
    style: columns
    columns: 4
    header: false
  Bookmarks:
    header: false
    style: columns
    columns: 10
