---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
statusStyle: "dot"
headerStyle: boxed
layout:
  Media Library & Downloads:
    icon: radarr
    style: row
    columns: 3

  Streaming & Devices:
    icon: jellyfin
    style: row
    columns: 3

  Server & Network Tools:
    icon: truenas-scale
    style: column

  System Monitoring:
    icon: mongodb
    style: column

  Smart Home Automation:
    icon: selfhosted-light
    style: column

  Turtle Apps:
    icon: https://magnet-feed-sync.pkarpovich.space/group-logo.png
    style: row
    columns: 3
